# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sharedalink
# ------
service: FireflyCompanionApi

custom:
  dynamodb:
    connections:
      name: ${self:service}-connections
      billingMode: PAY_PER_REQUEST
      attributeDefinitions:
        - AttributeName: channel_id
          AttributeType: S
        - AttributeName: connection_id
          AttributeType: S
      keySchema:
        - AttributeName: channel_id
          KeyType: HASH
        - AttributeName: connection_id
          KeyType: RANGE
      timeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
    events:
      name: ${self:service}-events
      billingMode: PAY_PER_REQUEST
      attributeDefinitions:
        - AttributeName: game_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      keySchema:
        - AttributeName: game_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
  tableArn:
    connections: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamodb.connections.name}
    events: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamodb.events.name}

provider:
  name: aws
  runtime: python3.12
  region: eu-west-1
  environment:
    CONNECTIONS_TABLE: ${self:custom.dynamodb.connections.name}
    EVENTS_TABLE: ${self:custom.dynamodb.events.name}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource:
        - ${self:custom.tableArn.connections}
        - ${self:custom.tableArn.events}
    - Effect: "Allow"
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - arn:aws:execute-api:${self:provider.region}:*:*/*/@connections/*

functions:
  onConnect:
    handler: src/app.connect
    events:
      - websocket: $connect
  onDisconnect:
    handler: src/app.disconnect
    events:
      - websocket: $disconnect
  onMessage:
    handler: src/app.message
    events:
      - websocket: $default

resources:
  Resources:
    ConnectionsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties: 
        TableName: ${self:custom.dynamodb.connections.name}
        AttributeDefinitions: 
          - AttributeName: channel_id
            AttributeType: S
          - AttributeName: connection_id
            AttributeType: S
        KeySchema: 
          - AttributeName: channel_id
            KeyType: HASH
          - AttributeName: connection_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: ttl
        Tags:
          - Key: Environment
            Value: dev
    EventsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties: 
        TableName: ${self:custom.dynamodb.events.name}
        AttributeDefinitions: 
          - AttributeName: game_id
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: game_id
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: Environment
            Value: dev

plugins:
  - serverless-python-requirements
  - serverless-dynamodb-local
  - serverless-offline