# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sharedalink
# "service" is the name of this project. This will also be added to your AWS resource names.
service: FireflyCompanionApi

custom:
  wsgi:
    app: app.app
  dynamodb:
    connections:
      name: ${self:service}-connections
      table: connections
      attributeDefinitions:
        - AttributeName: channel_id
          AttributeType: S
        - AttributeName: connection_id
          AttributeType: S
      keySchema:
        - AttributeName: channel_id
          KeyType: HASH
        - AttributeName: connection_id
          KeyType: RANGE
      timeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      billingMode: PAY_PER_REQUEST

provider:
  name: aws
  runtime: python3.12
  region: eu-west-1
  environment:
    CONNECTIONS_TABLE: ${self:custom.dynamodb.connections.name}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamodb.connections.name}
    - Effect: "Allow"
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - arn:aws:execute-api:${self:provider.region}:*:*/*/@connections/*

functions:
  onConnect:
    handler: src/app.connect
    environment:
      CONNECTIONS_TABLE: ${self:custom.dynamodb.connections.name}
    events:
      - websocket: $connect
  onDisconnect:
    handler: src/app.disconnect
    environment:
      CONNECTIONS_TABLE: ${self:custom.dynamodb.connections.name}
    events:
      - websocket: $disconnect
  onMessage:
    handler: src/app.message
    environment:
      CONNECTIONS_TABLE: ${self:custom.dynamodb.connections.name}
    events:
      - websocket: $default

resources:
  Resources:
    ConnectionsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties: 
        TableName: ${self:custom.dynamodb.connections.name}
        AttributeDefinitions: 
          - AttributeName: channel_id
            AttributeType: S
          - AttributeName: connection_id
            AttributeType: S
        KeySchema: 
          - AttributeName: channel_id
            KeyType: HASH
          - AttributeName: connection_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: ttl
        Tags:
          - Key: Environment
            Value: dev

plugins:
  - serverless-python-requirements
  - serverless-dynamodb-local
  - serverless-offline