version: "3.8"

services:
  devenv:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - AWS_PAGER
      - PYNAMODB_CONFIG=/etc/pynamodb/global_default_settings.py
      - PYTHONBREAKPOINT=remote_pdb.set_trace
      - REMOTE_PDB_HOST=0.0.0.0
      - REMOTE_PDB_PORT=33333
      - PIP_QUIET=1
    networks:
      - devenv

  dynamodb:
    image: amazon/dynamodb-local
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - devenv

networks:
  devenv:
    driver: bridge